
test:
  company: Rentify CR CTEST
  username: Rentify API CR CTEST
  password: lequ1li8di
  wsdl: "/Users/alex/dev/ruby/work/rentify/php-callcredit/CallReport71_PHP/Schemas/CallReport7.wsdl"

production:
  company: pone
  username: ptwo
  password: pthree
